export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

export const SET_CATEGORIAS = 'SET_CATEGORIAS';
export const SET_CATEGORIAS_CARGANDO = 'SET_CATEGORIAS_CARGANDO';
export const UNSET_CATEGORIAS_CARGANDO = 'UNSET_CATEGORIAS_CARGANDO';
