export let peliculas = [
	{
		adult: false,
		backdrop_path: '/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg',
		genre_ids: [35, 80],
		id: 337404,
		original_language: 'en',
		original_title: 'Cruella',
		overview:
			'"Cruella" se sumerge en la juventud rebelde de uno de los villanos más conocidos -y más de moda-, nada menos que la legendaria Cruella de Vil. Emma Stone encarna a Estella, alias Cruella, junto a Emma Thompson como la Baronesa, la directora de una prestigiosa firma de moda que convierte a Estella en una incipiente diseñadora. La cinta está ambientada en el contexto del punk-rock londinense de los 70.',
		popularity: 7516.105,
		poster_path: '/5bsApWAUqb0jeXtHPjKQ6MZOtZJ.jpg',
		release_date: '2021-05-26',
		title: 'Cruella',
		video: false,
		vote_average: 8.7,
		vote_count: 2099
	},
	{
		adult: false,
		backdrop_path: '/jw6ASGRT2gi8EjCImpGtbiJ9NQ9.jpg',
		genre_ids: [27],
		id: 632357,
		original_language: 'en',
		original_title: 'The Unholy',
		overview:
			'Se centra en un periodista caído en desgracia que descubre una serie de aparentes milagros acaecidos en un pequeño pueblo de Nueva Inglaterra, aplicándolos para devolver su carrera al estrellato. Lo que desconoce es que estos milagros esconden una cara mucho más oscura de lo que él cree.',
		popularity: 3962.67,
		poster_path: '/hPoOn553ARmSQl0ChKTlGDvYq9x.jpg',
		release_date: '2021-03-31',
		title: 'Ruega por nosotros',
		video: false,
		vote_average: 7.1,
		vote_count: 827
	},
	{
		adult: true,
		backdrop_path: '/77tui163estZrQ78NBggqDB4n2C.jpg',
		genre_ids: [28, 80],
		id: 637649,
		original_language: 'en',
		original_title: 'Wrath of Man',
		overview:
			'La historia sigue a H, un hombre frío y misterioso que trabaja en una empresa de camiones blindados responsable de mover cientos de millones de dólares por Los Ángeles cada semana.',
		popularity: 3865.286,
		poster_path: '/emM894kjspdQsHyTAF7sjRNlbTr.jpg',
		release_date: '2021-04-22',
		title: 'Despierta la furia',
		video: false,
		vote_average: 7.9,
		vote_count: 745
	},
	{
		adult: false,
		backdrop_path: '/9WlJFhOSCPnaaSmsrv0B4zA8iUb.jpg',
		genre_ids: [28, 27, 53, 80],
		id: 503736,
		original_language: 'en',
		original_title: 'Army of the Dead',
		overview:
			'Un grupo de mercenarios decide llevar a cabo el mayor atraco que jamás se haya realizado en la ciudad de Las Vegas justo después de que se produzca una epidemia de muertos vivientes. Para ello tendrán que adentrarse en una zona de cuarentena, con los riesgos que ello conlleva.',
		popularity: 2488.045,
		poster_path: '/zVXLDoEskRVUl8SaRh2lieY5STg.jpg',
		release_date: '2021-05-14',
		title: 'Ejército de los muertos',
		video: false,
		vote_average: 6.6,
		vote_count: 1430
	},
	{
		adult: false,
		backdrop_path: '/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg',
		genre_ids: [28, 14, 12],
		id: 460465,
		original_language: 'en',
		original_title: 'Mortal Kombat',
		overview:
			'Un boxeador fracasado descubre un secreto familiar que lo lleva a un torneo místico llamado Mortal Kombat donde se encuentra con un grupo de guerreros que luchan hasta la muerte para salvar los reinos del malvado hechicero Shang Tsung.',
		popularity: 2027.074,
		poster_path: '/t2GbiMJfO8txoihdJC8RsfK1ds7.jpg',
		release_date: '2021-04-07',
		title: 'Mortal Kombat',
		video: false,
		vote_average: 7.5,
		vote_count: 2919
	},
	{
		adult: true,
		backdrop_path: '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
		genre_ids: [28, 12, 878],
		id: 399566,
		original_language: 'en',
		original_title: 'Godzilla vs. Kong',
		overview:
			'Godzilla y Kong, dos de las fuerzas más poderosas de un planeta habitado por todo tipo de aterradoras criaturas, se enfrentan en un espectacular combate que sacude los cimientos de la humanidad. Monarch (Kyle Chandler) se embarca en una misión de alto riesgo y pone rumbo hacia territorios inexplorados para descubrir los orígenes de estos dos titanes, en un último esfuerzo por tratar de salvar a dos bestias que parecen tener las horas contadas sobre la faz de la Tierra.',
		popularity: 1913.072,
		poster_path: '/yJTk4eqQd9Yo5REpFbTSOMkbSgn.jpg',
		release_date: '2021-03-24',
		title: 'Godzilla vs. Kong',
		video: false,
		vote_average: 8.1,
		vote_count: 5876
	},
	{
		adult: false,
		backdrop_path: '/fPGeS6jgdLovQAKunNHX8l0avCy.jpg',
		genre_ids: [28, 53, 10752],
		id: 567189,
		original_language: 'en',
		original_title: "Tom Clancy's Without Remorse",
		overview:
			'Un ex Navy SEAL convertido en agente de la CIA busca venganza después de que su novia es asesinada por un narcotraficante de Baltimore.',
		popularity: 1646.786,
		poster_path: '/3A2owG58gqx8fzRWhVOMAO6lbWq.jpg',
		release_date: '2021-04-29',
		title: 'Sin remordimientos',
		video: false,
		vote_average: 7.2,
		vote_count: 1126
	},
	{
		adult: false,
		backdrop_path: '/ouOojiypBE6CD1aqcHPVq7cJf2R.jpg',
		genre_ids: [53, 18, 28, 9648],
		id: 578701,
		original_language: 'en',
		original_title: 'Those Who Wish Me Dead',
		overview:
			'Un adolescente testigo de un asesinato es perseguido por dos asesinos gemelos a través de las tierras salvajes de Montana. Aunque cuenta con un experto de la supervivencia para evitar que los secuaces le den caza, un incendio cercano pronto amenaza con robar la vida de todos los implicados.',
		popularity: 1541.871,
		poster_path: '/tu6kz9Ejm7wljiO58waAuwn1miV.jpg',
		release_date: '2021-05-05',
		title: 'Aquellos que desean mi muerte',
		video: false,
		vote_average: 7,
		vote_count: 424
	},
	{
		adult: true,
		backdrop_path: '/yyWNPhP1HR4BTLErHcZwIUsMBvA.jpg',
		genre_ids: [80, 18, 9648, 53],
		id: 823855,
		original_language: 'en',
		original_title: 'I Am All Girls',
		overview:
			'Una implacable inspectora encuentra afinidades con un asesino que mata a los criminales que dirigen una poderosa red de tráfico de menores.',
		popularity: 1284.3,
		poster_path: '/jAzX5TSKREp3Mhq7nqew4DcXjRZ.jpg',
		release_date: '2021-05-14',
		title: 'Yo soy todas ellas',
		video: false,
		vote_average: 6.8,
		vote_count: 102
	},
	{
		adult: false,
		backdrop_path: '/efrdAWS63s8TTWdrI2uNdIhn1dj.jpg',
		genre_ids: [53, 28, 80],
		id: 808023,
		original_language: 'en',
		original_title: 'The Virtuoso',
		overview:
			'Un asesino profesional debe localizar y matar a su último objetivo para satisfacer una deuda pendiente con su mentor. Pero la única información que se le ha dado es la hora y el lugar donde encontrar a su presa: las 5 de la tarde en un restaurante rústico en la ciudad decadente. Sin nombre, sin descripción, nada. Cuando llega al lugar, hay varios objetivos posibles, incluido el sheriff del condado. Poniendo en peligro su vida, el asesino se embarca en una cacería humana para encontrar al objetivo y cumplir su misión. Pero el peligro aumenta cuando los encuentros eróticos con una mujer lugareña amenazan con descarrilar su tarea.',
		popularity: 1303.11,
		poster_path: '/bhVAB3rdSRZjhy6rr5nPy274EIx.jpg',
		release_date: '2021-04-30',
		title: 'El virtuoso',
		video: false,
		vote_average: 6.2,
		vote_count: 115
	},
	{
		adult: false,
		backdrop_path: '/7JENyUT8ABxcvrcijDBVpdjgCY9.jpg',
		genre_ids: [53, 27, 9648],
		id: 602734,
		original_language: 'en',
		original_title: 'Spiral: From the Book of Saw',
		overview:
			'El detective descarado Ezekiel "Zeke" Banks, y su compañero novato, se hacen cargo de una espeluznante investigación sobre varios asesinatos espansosos. Zeke, involuntariamente, se vera atrapado en el  morboso juego del asesino.',
		popularity: 2296.001,
		poster_path: '/vgpzkh96GnlRxUYZuOpdZT78T2Q.jpg',
		release_date: '2021-05-12',
		title: 'Spiral: Saw',
		video: false,
		vote_average: 6.6,
		vote_count: 239
	},
	{
		adult: false,
		backdrop_path: '/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg',
		genre_ids: [28, 53, 80, 35],
		id: 615457,
		original_language: 'en',
		original_title: 'Nobody',
		overview:
			'Hutch Mansell, un padre de familia que aguanta con resignación y sin defenderse los golpes de la vida. Un don nadie.  Una noche, cuando dos ladrones entran en su casa, Hutch decide no actuar y no trata de defenderse ni al él mismo ni a su familia, convencido de que solo así evitará una escalada de violencia. Tras el ataque, su hija adolescente Blake no oculta su decepción, y su esposa Becca se aleja todavía más.',
		popularity: 1272.356,
		poster_path: '/ddO5a3tMPpQutSDQO1bESgLWadB.jpg',
		release_date: '2021-03-26',
		title: 'Nadie',
		video: false,
		vote_average: 8.4,
		vote_count: 1904
	},
	{
		adult: false,
		backdrop_path: '/hJuDvwzS0SPlsE6MNFOpznQltDZ.jpg',
		genre_ids: [16, 12, 14, 10751, 28],
		id: 527774,
		original_language: 'en',
		original_title: 'Raya and the Last Dragon',
		overview:
			'Raya, una niña de gran espíritu aventurero,  se embarca en la búsqueda del último dragón del mundo con el objetivo de devolver el equilibrio a Kumandra, un lejano y recóndito territorio habitado por una civilización milenaria.',
		popularity: 1274.838,
		poster_path: '/4Q9uU3mN5Y1Q04FWlqU2Mu3UAen.jpg',
		release_date: '2021-03-03',
		title: 'Raya y el último dragón',
		video: false,
		vote_average: 8.2,
		vote_count: 3190
	},
	{
		adult: false,
		backdrop_path: '/xrAaJAn3hqkInq5kE1AGJqIGXyT.jpg',
		genre_ids: [27],
		id: 573680,
		original_language: 'en',
		original_title: 'The Banishing',
		overview:
			'The Banishing cuenta la historia de la casa más encantada de Inglaterra. En la década de 1930, un joven reverendo, su esposa y su hija se mudan a una mansión con un secreto espantoso.',
		popularity: 1133.628,
		poster_path: '/hvcmPSUYyRLwP4tBy3rLqWEEmvM.jpg',
		release_date: '2021-04-29',
		title: 'El destierro',
		video: false,
		vote_average: 6.1,
		vote_count: 20
	},
	{
		adult: false,
		backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
		genre_ids: [28, 12, 14, 878],
		id: 791373,
		original_language: 'en',
		original_title: "Zack Snyder's Justice League",
		overview:
			'Con la determinación de asegurar que el sacrificio definitivo de Superman no fue en vano, Bruce Wayne une fuerzas con Diana Prince para reclutar a un equipo de metahumanos que protejan el mundo de una amenaza inminente de proporciones catastróficas. La tarea es más difícil de lo que Bruce imaginaba, ya que cada uno de los reclutas deberá enfrentarse a sus propios demonios para trascender aquello que los detenía, para unirse y formar de manera definitiva una liga de héroes sin precedentes. Ahora unidos, Batman, Wonder Woman, Aquaman, Cyborg y Flash deberán salvar al planeta de la amenaza de Steppenwolf, DeSaad y Darkseid, antes de que sea demasiado tarde.',
		popularity: 1276.784,
		poster_path: '/rkuvJnamPl3xW9wKJsIS6qkmOCW.jpg',
		release_date: '2021-03-18',
		title: 'La Liga de la Justicia de Zack Snyder',
		video: false,
		vote_average: 8.5,
		vote_count: 5703
	},
	{
		adult: false,
		backdrop_path: '/z2UtGA1WggESspi6KOXeo66lvLx.jpg',
		genre_ids: [878, 53, 27],
		id: 520763,
		original_language: 'en',
		original_title: 'A Quiet Place Part II',
		overview:
			'Los Abbott están de vuelta. Después de los eventos ocurridos en Un lugar tranquilo (2018) se enfrentarán a los terrores del mundo exterior. Evelyn (Emily Blunt) junto con sus hijos Regan (Millicent Simmonds) y Marcus (Noah Jupe) además de su bebé, se adentrarán en los bosques, decididos a traspasar los límites y adentrarse en lo desconocido.',
		popularity: 1191.119,
		poster_path: '/95m7s0jg0UHP3bIuwZkA12fxTl9.jpg',
		release_date: '2021-05-21',
		title: 'Un lugar tranquilo 2',
		video: false,
		vote_average: 7.4,
		vote_count: 153
	},
	{
		adult: false,
		backdrop_path: '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg',
		genre_ids: [16, 28, 12, 14, 18],
		id: 635302,
		original_language: 'ja',
		original_title: '劇場版「鬼滅の刃」無限列車編',
		overview:
			'Tanjiro y sus compañeros se unen al Pilar de las Llamas Kyojuro Rengoku para investigar una misteriosa serie de desapariciones que han ocurrido dentro del “Tren Infinito”. Poco saben que Enmu, uno de los miembros de las Doce Lunas Demoníacas, también está a bordo y les ha preparado una trampa.',
		popularity: 1141.56,
		poster_path: '/3f4ETSwknZs74lmUYC7ENIMRBMP.jpg',
		release_date: '2020-10-16',
		title: 'Guardianes de la Noche: Tren infinito',
		video: false,
		vote_average: 8.4,
		vote_count: 1144
	},
	{
		adult: false,
		backdrop_path: '/rlNnwObbMu5G2FaOUlacnUIdIIA.jpg',
		genre_ids: [16, 35, 10751, 12],
		id: 726684,
		original_language: 'fr',
		original_title: 'Miraculous World: Shanghai, la légende de Ladydragon',
		overview:
			'Para unirse a Adrien en Shanghai, Marinette va a visitar a su tío Wang, quien celebra su cumpleaños. Pero tan pronto como llega a China, ¡le roban su bolso con Tikki!, lo que no le permite convertirse en una Ladybug en secreto! Privada y sola en la gran ciudad, Marinette acepta la ayuda de una joven muy ingeniosa, Fei. Las dos chicas se harán amigas y descubrirán la existencia de una nueva joya mágica, los Prodigios, que Hawk Moth, también presente en Shanghai, ha estado buscando durante mucho tiempo...',
		popularity: 1087.281,
		poster_path: '/tf9nWFyJ745mBFkXZtPWabDYBR3.jpg',
		release_date: '2021-04-04',
		title: 'Miraculous World Shanghai, la leyenda de Ladydragón',
		video: false,
		vote_average: 7.9,
		vote_count: 384
	},
	{
		adult: false,
		backdrop_path: '/8cgPwMpdpSbWCoaqqp9eWPRtgw5.jpg',
		genre_ids: [18, 27, 878, 53],
		id: 710871,
		original_language: 'th',
		original_title: 'Ghost Lab ฉีกกฎทดลองผี',
		overview:
			'Después de que un experimento de laboratorio sobre el más allá sale mal, dos médicos se obsesionan peligrosamente con obtener pruebas científicas de la existencia de los fantasmas.',
		popularity: 1162.37,
		poster_path: '/5eLNJYehI3VwIe5S7Yz3uxVWVOa.jpg',
		release_date: '2021-05-26',
		title: 'El experimento fantasma',
		video: false,
		vote_average: 6,
		vote_count: 23
	},
	{
		adult: false,
		backdrop_path: '/fejok33Ijc6SppiEU1cfwA9Mo2.jpg',
		genre_ids: [28, 80, 18],
		id: 717192,
		original_language: 'nl',
		original_title: 'Ferry',
		overview:
			'Antes de crear un emporio de la droga, Ferry Bouman vuelve a su ciudad para vengarse. Allí se pondrá a prueba su lealtad y el amor le cambiará la vida.',
		popularity: 946.4,
		poster_path: '/w6n1pu9thpCVHILejsuhKf3tNCV.jpg',
		release_date: '2021-05-14',
		title: 'Ferry',
		video: false,
		vote_average: 7,
		vote_count: 83
	}
];
